name: Run Hello World Programs

on:
  push:
    branches:
      - main

jobs:
  run_hello_worlds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2