name: Run Hello World Programs

on:
  push:
    branches:
      - main

jobs:
  run_hello_worlds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup C++ environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install C++ compiler
      run: sudo apt-get install -y g++
    - name: Setup Rust environment
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Compile and run C++ Hello World program
      run: |
        g++ hello_world.cpp -o hello_world
        ./hello_world > output.txt
    - name: Test C++ Hello World output
      run: grep "Hello, World!" output.txt
    - name: Compile and run Rust Hello World program
      run: |
        cd rust_hello_world
        rustc main.rs -o rust_hello_world
        ./rust_hello_world > ../rust_output.txt
        cd ..
    - name: Test Rust Hello World output
      run: grep "Hello, World!" rust_output.txt
